udo: false

language: python
python:
  - "3.5"

install:
  - ./install-inotify-wrapper.sh
  - pip install .
  - pip install -r requirements.txt

script: py.test -v --cov=botbot/

after_success:
  - coveralls
